name: Clone Example

on: push

jobs:
  clone-job:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Show files
        run: ls -la
